image: "rust:latest"

stages:
    - lint
    - test

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script: cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - rustup component add clippy
        - apt update -yqq
        - apt install -yqq clang libpq-dev
    script: cargo clippy --all-features --all-targets -- --deny warnings

test:
    parallel:
        matrix:
            - MODE: ['debug', 'release']
    stage: test
    before_script:
        - apt update -yqq
        - apt install -yqq clang libpq-dev
    script: |
        if [[ $MODE == "release" ]]
        then
            cargo test --workspace --all-features --release
        else
            cargo test --workspace --all-features
        fi
