[package]
name = "sav"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
pretty_env_logger = "0.4"
mime = "0.3"
rocket = "0.4"
multipart = "0.17"
serde = "1.0"
serde_derive = "1.0"
tera = "1.5"
tera-hot = "0.2"
tree_magic = "0.2"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["serve"]

[dependencies.elephantry]
version = "1.0"
features = ["date", "serde-support"]

[dependencies.elephantry-extras]
version = "0.1"
features = ["serde", "tera"]
