[package]
name = "sav"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"
license = "MIT"

[dependencies]
mime = "0.3"
multipart = "0.18"
rocket = "0.5.0-rc.3"
serde = "1.0"
serde_derive = "1.0"
tera = "1.5"
thiserror = "1.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.3"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.3"
features = ["tera"]

[dependencies.elephantry]
path = "../../elephantry/elephantry/core"
version = "3.0"
features = ["date", "rocket", "serde"]

[dependencies.elephantry-extras]
version = "0.4"
features = ["serde", "tera"]
