<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Expense
 *
 * Structure class for relation public.expense.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Expense extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('public.expense')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('serial', 'varchar')
            ->addField('name', 'varchar')
            ->addField('url', 'varchar')
            ->addField('shop', 'varchar')
            ->addField('warranty', 'interval')
            ->addField('price', 'float4')
            ->addField('trashed_at', 'timestamp')
            ;
    }
}
