index:
    path: /
    defaults: { _controller: app.controller.index:index }

expenses_add:
    path: /expenses/add
    defaults: { _controller: app.controller.expenses:add }
    methods: [GET]

expenses_create:
    path: /expenses/add
    defaults: { _controller: app.controller.expenses:create }
    methods: [POST]

expenses_edit:
    path: /expenses/{id}/edit
    defaults: { _controller: app.controller.expenses:edit }
    methods: [GET]

expenses_save:
    path: /expenses/{id}/edit
    defaults: { _controller: app.controller.expenses:save }
    methods: [POST]

expenses_delete:
    path: /expenses/{id}/delete
    defaults: { _controller: app.controller.expenses:delete }
    methods: [GET]

expenses_trash:
    path: /expenses/{id}/trash
    defaults: { _controller: app.controller.expenses:trash }
    methods: [GET]

expenses_untrash:
    path: /expenses/{id}/untrash
    defaults: { _controller: app.controller.expenses:untrash }
    methods: [GET]

expenses_media:
    path: /expenses/{id}/{type}
    defaults: { _controller: app.controller.expenses:media }
    methods: [GET]
